name: Bug Report
description: Provide information about a project to be added to awesome-connect-iq list or a project that shouldn't be included.
title: "Project proposal: "
labels: ["triage"]
body:
- type: markdown
  attributes:
    value: |
      Provide information about a project to be added to awesome-connect-iq list or a project that shouldn't be included.

      Please, note, that this issue type is about a project (Watch App, Widget, etc.), not learning materials (tutorial, video, etc.).
      The latter has its own issue type. <<TODO: Add link>>     
- type: dropdown
  id: decision
  attributes:
    label: Decision
    description: Is this PR for including a project in the list, or not including the project?
    options:
      - Include
      - Do not include
  validations:
    required: true      
 