name: Bug Report
description: Provide information about a project to be added to awesome-connect-iq list or a project that shouldn't be included.
title: "Project proposal: "
labels: ["triage"]
body:
- type: markdown
  attributes:
    value: |
      Please, note, that this issue type is about a project (Watch App, Widget, etc.), not learning materials (tutorial, video, etc.).
      The latter has its own issue type. <<TODO: Add link>>      https://github.com/karol-brejna-i/awesome-connect-iq/issues/new/choose
- type: markdown
  attributes:
    value: |
      # Summary

      Provide information about a project to be added to awesome-connect-iq list or a project that shouldn't be included.
- type: dropdown
  id: decision
  attributes:
    label: Decision
    description: Is this PR for including a project in the list, or not including the project?
    options:
      - Include
      - Do not include
  validations:
    required: true
- type: textarea
  id: summary
  attributes:
    label: Justification
    description: Include some summary, why the project should be accepted/rejected.
    placeholder: Tell us what you think!
    value: "..."
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      # Information about the project

- type: input
  id: projectUrl
  attributes:
    label: Bug prevalence
    description: "How often do you or others encounter this bug?"
    placeholder: "Example: Whenever I visit the personal account page (1-2 times a week)"
  validations:
    required: true      
- type: dropdown
  id: license
  attributes:
    label: What is the project license?
    multiple: false
    options:
      - Apache-2.0
      - MIT
      - Some
      - Other (describe in "Jaustification")
      - Unknown
  # Repo URL	...
  # Project type	Audio Content Provider/Data Field/Device App/Widget/Watch Face/Collection
  # License	license type/no info
  # Connect IQ Store URL	url, if it is available in the store
  # Does it run in the simulator?	Yes/no. Which device?
  # Does it run on a device?	Yes/no. Which device?
  # Good readme/docs	yes/no/short comment
  # "Clean code"	yes/no/short comment