# This is a basic workflow to help you get started with Actions

name: scheduled

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  # This workflow contains a single job called "build"
  echoer:
      runs-on: ubuntu-latest
      steps:
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: |
            echo "$GITHUB_CONTEXT"
